apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: trustyai
  app.kubernetes.io/part-of: trustyai
resources:
- trustyai-deployment.yaml
- ../servicemonitors
- route.yaml
- pvc.yaml
configMapGenerator:
  - name: trustyai-config
    env: params.env
configurations:
  - params.yaml
vars:
  - name: image
    objref:
      kind: ConfigMap
      name: trustyai-config
      apiVersion: v1
    fieldref:
      fieldpath: data.image