blank_issues_enabled: true
contact_links:
  - name: Issues
    url: https://github.com/trustyai-explainability/trustyai-explainability/issues
    about: trustyai-explainability issues board
  - name: Question
    url: https://stackoverflow.com/questions/ask?tags=trustyai
    about: I have a question about how to use TrustyAI.
  - name: TrustyAI Slack chat
    url: https://odh-io.slack.com/archives/C03UFCVFFEY
    about: If you prefer live chat with the developers, we have a Slack chat where we all hang out.