---
openapi: 3.0.3
info:
  title: explainability-service API
  version: 999-SNAPSHOT
tags:
  - name: Disparate Impact Ratio Endpoint
    description: Disparate Impact Ratio (DIR) measures imbalances in classifications
      by calculating the ratio between the proportion of the majority and protected
      classes getting a particular outcome.
  - name: Statistical Parity Difference Endpoint
    description: Statistical Parity Difference (SPD) measures imbalances in classifications
      by calculating the difference between the proportion of the majority and protected
      classes getting a particular outcome.
paths:
  /consumer/kserve/v2:
    post:
      tags:
        - Consumer Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferencePayload'
      responses:
        "200":
          description: OK
  /info:
    get:
      tags:
        - Service Metadata Endpoint
      responses:
        "200":
          description: OK
  /metrics/dir:
    post:
      tags:
        - Disparate Impact Ratio Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseMetricRequest'
      responses:
        "200":
          description: OK
  /metrics/dir/definition:
    get:
      tags:
        - Disparate Impact Ratio Endpoint
      responses:
        "200":
          description: OK
    post:
      tags:
        - Disparate Impact Ratio Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DefinitionRequest'
      responses:
        "200":
          description: OK
  /metrics/dir/request:
    post:
      tags:
        - Disparate Impact Ratio Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseMetricRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
    delete:
      tags:
        - Disparate Impact Ratio Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleId'
      responses:
        "200":
          description: OK
  /metrics/dir/requests:
    get:
      tags:
        - Disparate Impact Ratio Endpoint
      responses:
        "200":
          description: OK
  /metrics/spd:
    post:
      tags:
        - Statistical Parity Difference Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseMetricRequest'
      responses:
        "200":
          description: OK
  /metrics/spd/definition:
    get:
      tags:
        - Statistical Parity Difference Endpoint
      responses:
        "200":
          description: OK
    post:
      tags:
        - Statistical Parity Difference Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DefinitionRequest'
      responses:
        "200":
          description: OK
  /metrics/spd/request:
    post:
      tags:
        - Statistical Parity Difference Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseMetricRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
    delete:
      tags:
        - Statistical Parity Difference Endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleId'
      responses:
        "200":
          description: OK
  /metrics/spd/requests:
    get:
      tags:
        - Statistical Parity Difference Endpoint
      responses:
        "200":
          description: OK
components:
  schemas:
    BaseMetricRequest:
      type: object
      properties:
        protectedAttribute:
          type: string
        favorableOutcome:
          $ref: '#/components/schemas/TypedValue'
        outcomeName:
          type: string
        privilegedAttribute:
          $ref: '#/components/schemas/TypedValue'
        unprivilegedAttribute:
          $ref: '#/components/schemas/TypedValue'
    DefinitionRequest:
      type: object
      properties:
        protectedAttribute:
          type: string
        favorableOutcome:
          $ref: '#/components/schemas/TypedValue'
        outcomeName:
          type: string
        privilegedAttribute:
          $ref: '#/components/schemas/TypedValue'
        unprivilegedAttribute:
          $ref: '#/components/schemas/TypedValue'
        metricValue:
          $ref: '#/components/schemas/JsonNode'
    InferencePayload:
      type: object
      properties:
        input:
          type: string
        output:
          type: string
    JsonNode:
      type: array
    ScheduleId:
      type: object
      properties:
        requestId:
          $ref: '#/components/schemas/UUID'
    TypedValue:
      type: object
      properties:
        type:
          type: string
        value:
          $ref: '#/components/schemas/JsonNode'
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
