apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: trustyai
  app.kubernetes.io/part-of: trustyai
resources:
  - ../default
  - ../servicemonitors
  - trustyai-configmap.yaml
