// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_predict_v2.proto

package org.kie.trustyai.connectors.kserve.v2.grpc;

public interface ModelReadyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inference.ModelReadyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the model to check for readiness.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the model to check for readiness.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The version of the model to check for readiness. If not given the
   * server will choose a version based on the model and internal policy.
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * The version of the model to check for readiness. If not given the
   * server will choose a version based on the model and internal policy.
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
