// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_predict_v2.proto

package org.kie.trustyai.connectors.kserve.v2.grpc;

public interface ServerLiveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inference.ServerLiveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * True if the inference server is live, false if not live.
   * </pre>
   *
   * <code>bool live = 1;</code>
   * @return The live.
   */
  boolean getLive();
}
