// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_predict_v2.proto

package org.kie.trustyai.connectors.kserve.v2.grpc;

public interface ServerLiveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inference.ServerLiveRequest)
    com.google.protobuf.MessageOrBuilder {
}
