// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_predict_v2.proto

package org.kie.trustyai.connectors.kserve.v2.grpc;

public interface ServerReadyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inference.ServerReadyRequest)
    com.google.protobuf.MessageOrBuilder {
}
