apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-trustyai
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: odh-manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: trustyai-manifests
          path: explainability-service/manifests/
      name: trustyai
  repos:
    - name: odh-manifests
      uri: https://api.github.com/repos/opendatahub-io/odh-manifests/tarball/master
    - name: trustyai-manifests
      uri: https://api.github.com/repos/trustyai-explainability/trustyai-explainability/tarball/main
  version: master
