services:
  trustyai:
    image: trustyai/trustyai-service:999-SNAPSHOT
    container_name: trustyai-service
    ports:
      - "8080:8080"
    environment:
      SERVICE_MODEL_NAME: "example"
      SERVICE_KSERVE_TARGET: "localhost"
      SERVICE_STORAGE_FORMAT: "PVC"
      SERVICE_DATA_FORMAT: "CSV"
      PVC_INPUT_FILENAME: "/inputs/income-biased-inputs.csv"
      PVC_OUTPUT_FILENAME: "/inputs/income-biased-outputs.csv"
      SERVICE_METRICS_SCHEDULE: "5s"
      SERVICE_BATCH_SIZE: 5000
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
volumes:
  prom_data:
