#!/bin/bash

# Change this if your project is not named opendatahub
export ODHPROJECT=${ODHPROJECT:-"opendatahub"}

millisecond=1
second=$(( 1000 * millisecond ))
minute=$(( 60 * second ))
fiveminute=$(( 300 * second ))
odhdefaulttimeout=$(( 1200 * second ))
odhdefaultinterval=$(( 10 ))

BLUE='\033[0;34m'
END='\033[0m'

function header() {
  echo
  echo -e $BLUE$1$END
}
