apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: demo-loan-nn-onnx-beta
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      runtime: ovms-1.x
      storageUri: "https://github.com/RobGeada/trustyai_april12_demo/blob/main/resources/loan_model_beta.onnx?raw=true" # update this