apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: model-mesh
  app.kubernetes.io/part-of: model-mesh
resources:
- ../default
- ../dependencies/quickstart.yaml
- ../dependencies/scripts
- ../prometheus
configMapGenerator:
  - name: mesh-parameters
    envs:
      - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: meshnamespace
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: monitoring-namespace
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.monitoring-namespace
  - name: odh-modelmesh
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-modelmesh
  - name: odh-mm-rest-proxy
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-mm-rest-proxy
  - name: odh-modelmesh-runtime-adapter
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-modelmesh-runtime-adapter
  - name: odh-modelmesh-controller
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-modelmesh-controller
  - name: odh-model-controller
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-model-controller
  - name: odh-openvino
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-openvino
configurations:
  - params.yaml
